name: Ransomware Framework CI/CD

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs to run
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      # Run tests
      - name: Run tests
        run: |
          pytest tests/

  lint:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Install linting tools
      - name: Install linting tools
        run: |
          pip install black flake8

      # Check code formatting with Black
      - name: Check formatting with Black
        run: |
          black --check ransomware_framework/ tests/

      # Check for linting errors with Flake8
      - name: Check for linting errors with Flake8
        run: |
          flake8 ransomware_framework/ tests/

  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel

      # Build the package
      - name: Build the package
        run: |
          python setup.py sdist bdist_wheel

      # Verify the built package
      - name: Verify the built package
        run: |
          pip install dist/*.whl